services:
  frontend-admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    container_name: frontend-admin-2100
    ports:
      - "8081:8081"
    restart: unless-stopped
